"""create greeting table

Revision ID: 9afc2d6cf6a9
Revises: 
Create Date: 2023-10-16 08:08:45.980504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9afc2d6cf6a9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('greeting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phrase', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('greeting')
    # ### end Alembic commands ###
